// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.6.1
// source: internal/controller/pb/controller.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// If not NONE, the reason for a scrape failure
type ScrapeError int32

const (
	// No error
	ScrapeError_NONE ScrapeError = 0
	// The request could not be made
	ScrapeError_INVALID_REQUEST ScrapeError = 1
	// The scrape timed out
	ScrapeError_TIMEOUT ScrapeError = 2
)

// Enum value maps for ScrapeError.
var (
	ScrapeError_name = map[int32]string{
		0: "NONE",
		1: "INVALID_REQUEST",
		2: "TIMEOUT",
	}
	ScrapeError_value = map[string]int32{
		"NONE":            0,
		"INVALID_REQUEST": 1,
		"TIMEOUT":         2,
	}
)

func (x ScrapeError) Enum() *ScrapeError {
	p := new(ScrapeError)
	*p = x
	return p
}

func (x ScrapeError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScrapeError) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_controller_pb_controller_proto_enumTypes[0].Descriptor()
}

func (ScrapeError) Type() protoreflect.EnumType {
	return &file_internal_controller_pb_controller_proto_enumTypes[0]
}

func (x ScrapeError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScrapeError.Descriptor instead.
func (ScrapeError) EnumDescriptor() ([]byte, []int) {
	return file_internal_controller_pb_controller_proto_rawDescGZIP(), []int{0}
}

// An instruction from the controller to agent of what to scrape
type ScrapeInstruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A list of URLs to scrape
	Urls []string `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *ScrapeInstruction) Reset() {
	*x = ScrapeInstruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_controller_pb_controller_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScrapeInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeInstruction) ProtoMessage() {}

func (x *ScrapeInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controller_pb_controller_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeInstruction.ProtoReflect.Descriptor instead.
func (*ScrapeInstruction) Descriptor() ([]byte, []int) {
	return file_internal_controller_pb_controller_proto_rawDescGZIP(), []int{0}
}

func (x *ScrapeInstruction) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

// Configuration update for workers
type WorkerConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A unique ID for the worker assigned by the controller
	WorkerId int32 `protobuf:"varint,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// The timeout the agent should use for each single page scrape operation
	SingleScrapeTimeoutMs int32 `protobuf:"varint,2,opt,name=single_scrape_timeout_ms,json=singleScrapeTimeoutMs,proto3" json:"single_scrape_timeout_ms,omitempty"`
}

func (x *WorkerConfig) Reset() {
	*x = WorkerConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_controller_pb_controller_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerConfig) ProtoMessage() {}

func (x *WorkerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controller_pb_controller_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerConfig.ProtoReflect.Descriptor instead.
func (*WorkerConfig) Descriptor() ([]byte, []int) {
	return file_internal_controller_pb_controller_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerConfig) GetWorkerId() int32 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

func (x *WorkerConfig) GetSingleScrapeTimeoutMs() int32 {
	if x != nil {
		return x.SingleScrapeTimeoutMs
	}
	return 0
}

// An instruction from the controller for an agent
type ControllerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*ControllerMessage_ScrapeInstruction
	//	*ControllerMessage_ConfigUpdate
	Message isControllerMessage_Message `protobuf_oneof:"message"`
}

func (x *ControllerMessage) Reset() {
	*x = ControllerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_controller_pb_controller_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControllerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerMessage) ProtoMessage() {}

func (x *ControllerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controller_pb_controller_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerMessage.ProtoReflect.Descriptor instead.
func (*ControllerMessage) Descriptor() ([]byte, []int) {
	return file_internal_controller_pb_controller_proto_rawDescGZIP(), []int{2}
}

func (m *ControllerMessage) GetMessage() isControllerMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *ControllerMessage) GetScrapeInstruction() *ScrapeInstruction {
	if x, ok := x.GetMessage().(*ControllerMessage_ScrapeInstruction); ok {
		return x.ScrapeInstruction
	}
	return nil
}

func (x *ControllerMessage) GetConfigUpdate() *WorkerConfig {
	if x, ok := x.GetMessage().(*ControllerMessage_ConfigUpdate); ok {
		return x.ConfigUpdate
	}
	return nil
}

type isControllerMessage_Message interface {
	isControllerMessage_Message()
}

type ControllerMessage_ScrapeInstruction struct {
	ScrapeInstruction *ScrapeInstruction `protobuf:"bytes,1,opt,name=scrape_instruction,json=scrapeInstruction,proto3,oneof"`
}

type ControllerMessage_ConfigUpdate struct {
	ConfigUpdate *WorkerConfig `protobuf:"bytes,2,opt,name=config_update,json=configUpdate,proto3,oneof"`
}

func (*ControllerMessage_ScrapeInstruction) isControllerMessage_Message() {}

func (*ControllerMessage_ConfigUpdate) isControllerMessage_Message() {}

type WorkerHandshake struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The version of nomad the agent is using
	NomadVersion int64 `protobuf:"varint,1,opt,name=nomad_version,json=nomadVersion,proto3" json:"nomad_version,omitempty"`
}

func (x *WorkerHandshake) Reset() {
	*x = WorkerHandshake{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_controller_pb_controller_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerHandshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHandshake) ProtoMessage() {}

func (x *WorkerHandshake) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controller_pb_controller_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHandshake.ProtoReflect.Descriptor instead.
func (*WorkerHandshake) Descriptor() ([]byte, []int) {
	return file_internal_controller_pb_controller_proto_rawDescGZIP(), []int{3}
}

func (x *WorkerHandshake) GetNomadVersion() int64 {
	if x != nil {
		return x.NomadVersion
	}
	return 0
}

// Information about a single page scrape operation
type ScrapeMetrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The total number of bytes downloaded during the operation
	ResponseSizeBytes int64 `protobuf:"varint,1,opt,name=response_size_bytes,json=responseSizeBytes,proto3" json:"response_size_bytes,omitempty"`
	// The number of URLs in the found_urls list
	NumFoundUrls int32 `protobuf:"varint,2,opt,name=num_found_urls,json=numFoundUrls,proto3" json:"num_found_urls,omitempty"`
	// How long this individual scrape took to execute
	ScrapeDurationMs int32 `protobuf:"varint,3,opt,name=scrape_duration_ms,json=scrapeDurationMs,proto3" json:"scrape_duration_ms,omitempty"`
}

func (x *ScrapeMetrics) Reset() {
	*x = ScrapeMetrics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_controller_pb_controller_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScrapeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeMetrics) ProtoMessage() {}

func (x *ScrapeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controller_pb_controller_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeMetrics.ProtoReflect.Descriptor instead.
func (*ScrapeMetrics) Descriptor() ([]byte, []int) {
	return file_internal_controller_pb_controller_proto_rawDescGZIP(), []int{4}
}

func (x *ScrapeMetrics) GetResponseSizeBytes() int64 {
	if x != nil {
		return x.ResponseSizeBytes
	}
	return 0
}

func (x *ScrapeMetrics) GetNumFoundUrls() int32 {
	if x != nil {
		return x.NumFoundUrls
	}
	return 0
}

func (x *ScrapeMetrics) GetScrapeDurationMs() int32 {
	if x != nil {
		return x.ScrapeDurationMs
	}
	return 0
}

// Information from scraping a single URL
type ScrapedData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The agent that scraped
	AgentId int32 `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// The URL scraped
	ScrapedUrl string `protobuf:"bytes,2,opt,name=scraped_url,json=scrapedUrl,proto3" json:"scraped_url,omitempty"`
	// The URLs found on the page
	FoundUrls []string `protobuf:"bytes,3,rep,name=found_urls,json=foundUrls,proto3" json:"found_urls,omitempty"`
	// Metrics from the scape
	Metrics *ScrapeMetrics `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	// If there was an error
	Error ScrapeError `protobuf:"varint,5,opt,name=error,proto3,enum=pb.ScrapeError" json:"error,omitempty"`
}

func (x *ScrapedData) Reset() {
	*x = ScrapedData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_controller_pb_controller_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScrapedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapedData) ProtoMessage() {}

func (x *ScrapedData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controller_pb_controller_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapedData.ProtoReflect.Descriptor instead.
func (*ScrapedData) Descriptor() ([]byte, []int) {
	return file_internal_controller_pb_controller_proto_rawDescGZIP(), []int{5}
}

func (x *ScrapedData) GetAgentId() int32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *ScrapedData) GetScrapedUrl() string {
	if x != nil {
		return x.ScrapedUrl
	}
	return ""
}

func (x *ScrapedData) GetFoundUrls() []string {
	if x != nil {
		return x.FoundUrls
	}
	return nil
}

func (x *ScrapedData) GetMetrics() *ScrapeMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *ScrapedData) GetError() ScrapeError {
	if x != nil {
		return x.Error
	}
	return ScrapeError_NONE
}

type WorkerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*WorkerMessage_Handshake
	//	*WorkerMessage_Data
	Message isWorkerMessage_Message `protobuf_oneof:"message"`
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_controller_pb_controller_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controller_pb_controller_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_internal_controller_pb_controller_proto_rawDescGZIP(), []int{6}
}

func (m *WorkerMessage) GetMessage() isWorkerMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *WorkerMessage) GetHandshake() *WorkerHandshake {
	if x, ok := x.GetMessage().(*WorkerMessage_Handshake); ok {
		return x.Handshake
	}
	return nil
}

func (x *WorkerMessage) GetData() *ScrapedData {
	if x, ok := x.GetMessage().(*WorkerMessage_Data); ok {
		return x.Data
	}
	return nil
}

type isWorkerMessage_Message interface {
	isWorkerMessage_Message()
}

type WorkerMessage_Handshake struct {
	Handshake *WorkerHandshake `protobuf:"bytes,1,opt,name=handshake,proto3,oneof"`
}

type WorkerMessage_Data struct {
	Data *ScrapedData `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*WorkerMessage_Handshake) isWorkerMessage_Message() {}

func (*WorkerMessage_Data) isWorkerMessage_Message() {}

var File_internal_controller_pb_controller_proto protoreflect.FileDescriptor

var file_internal_controller_pb_controller_proto_rawDesc = []byte{
	0x0a, 0x27, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x27, 0x0a,
	0x11, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x22, 0x64, 0x0a, 0x0c, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x18, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x5f, 0x73, 0x63,
	0x72, 0x61, 0x70, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x5f, 0x6d, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x15, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x53, 0x63, 0x72,
	0x61, 0x70, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4d, 0x73, 0x22, 0x9f, 0x01, 0x0a,
	0x11, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x46, 0x0a, 0x12, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x5f, 0x69, 0x6e, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x11, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x49,
	0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x37, 0x0a, 0x0d, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x36,
	0x0a, 0x0f, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b,
	0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6e, 0x6f, 0x6d, 0x61, 0x64, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6e, 0x6f, 0x6d, 0x61, 0x64, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x93, 0x01, 0x0a, 0x0d, 0x53, 0x63, 0x72, 0x61, 0x70,
	0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x2e, 0x0a, 0x13, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x6e, 0x75, 0x6d, 0x5f,
	0x66, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x6e, 0x75, 0x6d, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x55, 0x72, 0x6c, 0x73, 0x12, 0x2c,
	0x0a, 0x12, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x73, 0x63, 0x72, 0x61,
	0x70, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x22, 0xbc, 0x01, 0x0a,
	0x0b, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x08,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x63, 0x72, 0x61, 0x70,
	0x65, 0x64, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x63,
	0x72, 0x61, 0x70, 0x65, 0x64, 0x55, 0x72, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x6f, 0x75, 0x6e,
	0x64, 0x5f, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x66, 0x6f,
	0x75, 0x6e, 0x64, 0x55, 0x72, 0x6c, 0x73, 0x12, 0x2b, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63,
	0x72, 0x61, 0x70, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x07, 0x6d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x12, 0x25, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x76, 0x0a, 0x0d, 0x57,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x33, 0x0a, 0x09,
	0x68, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x48, 0x61, 0x6e, 0x64, 0x73,
	0x68, 0x61, 0x6b, 0x65, 0x48, 0x00, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b,
	0x65, 0x12, 0x25, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2a, 0x39, 0x0a, 0x0b, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f,
	0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10,
	0x01, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x49, 0x4d, 0x45, 0x4f, 0x55, 0x54, 0x10, 0x02, 0x32, 0x4a,
	0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x3c, 0x0a, 0x0c,
	0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x11, 0x2e, 0x70,
	0x62, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a,
	0x15, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x73, 0x69, 0x64, 0x65, 0x78, 0x2f,
	0x6e, 0x6f, 0x6d, 0x61, 0x64, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_controller_pb_controller_proto_rawDescOnce sync.Once
	file_internal_controller_pb_controller_proto_rawDescData = file_internal_controller_pb_controller_proto_rawDesc
)

func file_internal_controller_pb_controller_proto_rawDescGZIP() []byte {
	file_internal_controller_pb_controller_proto_rawDescOnce.Do(func() {
		file_internal_controller_pb_controller_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_controller_pb_controller_proto_rawDescData)
	})
	return file_internal_controller_pb_controller_proto_rawDescData
}

var file_internal_controller_pb_controller_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_controller_pb_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_controller_pb_controller_proto_goTypes = []any{
	(ScrapeError)(0),          // 0: pb.ScrapeError
	(*ScrapeInstruction)(nil), // 1: pb.ScrapeInstruction
	(*WorkerConfig)(nil),      // 2: pb.WorkerConfig
	(*ControllerMessage)(nil), // 3: pb.ControllerMessage
	(*WorkerHandshake)(nil),   // 4: pb.WorkerHandshake
	(*ScrapeMetrics)(nil),     // 5: pb.ScrapeMetrics
	(*ScrapedData)(nil),       // 6: pb.ScrapedData
	(*WorkerMessage)(nil),     // 7: pb.WorkerMessage
}
var file_internal_controller_pb_controller_proto_depIdxs = []int32{
	1, // 0: pb.ControllerMessage.scrape_instruction:type_name -> pb.ScrapeInstruction
	2, // 1: pb.ControllerMessage.config_update:type_name -> pb.WorkerConfig
	5, // 2: pb.ScrapedData.metrics:type_name -> pb.ScrapeMetrics
	0, // 3: pb.ScrapedData.error:type_name -> pb.ScrapeError
	4, // 4: pb.WorkerMessage.handshake:type_name -> pb.WorkerHandshake
	6, // 5: pb.WorkerMessage.data:type_name -> pb.ScrapedData
	7, // 6: pb.Controller.WorkerStream:input_type -> pb.WorkerMessage
	3, // 7: pb.Controller.WorkerStream:output_type -> pb.ControllerMessage
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_internal_controller_pb_controller_proto_init() }
func file_internal_controller_pb_controller_proto_init() {
	if File_internal_controller_pb_controller_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_controller_pb_controller_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ScrapeInstruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_controller_pb_controller_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*WorkerConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_controller_pb_controller_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ControllerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_controller_pb_controller_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*WorkerHandshake); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_controller_pb_controller_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ScrapeMetrics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_controller_pb_controller_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ScrapedData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_controller_pb_controller_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*WorkerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_controller_pb_controller_proto_msgTypes[2].OneofWrappers = []any{
		(*ControllerMessage_ScrapeInstruction)(nil),
		(*ControllerMessage_ConfigUpdate)(nil),
	}
	file_internal_controller_pb_controller_proto_msgTypes[6].OneofWrappers = []any{
		(*WorkerMessage_Handshake)(nil),
		(*WorkerMessage_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_controller_pb_controller_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_controller_pb_controller_proto_goTypes,
		DependencyIndexes: file_internal_controller_pb_controller_proto_depIdxs,
		EnumInfos:         file_internal_controller_pb_controller_proto_enumTypes,
		MessageInfos:      file_internal_controller_pb_controller_proto_msgTypes,
	}.Build()
	File_internal_controller_pb_controller_proto = out.File
	file_internal_controller_pb_controller_proto_rawDesc = nil
	file_internal_controller_pb_controller_proto_goTypes = nil
	file_internal_controller_pb_controller_proto_depIdxs = nil
}
