// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: internal/controller/pb/controller.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// If not NONE, the reason for a scrape failure
type URLRequestErrorCode int32

const (
	// No error
	URLRequestErrorCode_NONE URLRequestErrorCode = 0
	// Check metrics.http_status_code
	URLRequestErrorCode_CHECK_RESPONSE_CODE URLRequestErrorCode = 1
	// The request could not be made
	URLRequestErrorCode_INVALID_REQUEST URLRequestErrorCode = 2
	// The request timed out
	URLRequestErrorCode_TIMEOUT URLRequestErrorCode = 3
)

// Enum value maps for URLRequestErrorCode.
var (
	URLRequestErrorCode_name = map[int32]string{
		0: "NONE",
		1: "CHECK_RESPONSE_CODE",
		2: "INVALID_REQUEST",
		3: "TIMEOUT",
	}
	URLRequestErrorCode_value = map[string]int32{
		"NONE":                0,
		"CHECK_RESPONSE_CODE": 1,
		"INVALID_REQUEST":     2,
		"TIMEOUT":             3,
	}
)

func (x URLRequestErrorCode) Enum() *URLRequestErrorCode {
	p := new(URLRequestErrorCode)
	*p = x
	return p
}

func (x URLRequestErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (URLRequestErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_controller_pb_controller_proto_enumTypes[0].Descriptor()
}

func (URLRequestErrorCode) Type() protoreflect.EnumType {
	return &file_internal_controller_pb_controller_proto_enumTypes[0]
}

func (x URLRequestErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use URLRequestErrorCode.Descriptor instead.
func (URLRequestErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_internal_controller_pb_controller_proto_rawDescGZIP(), []int{0}
}

// Message for the bi-directional stream
type ScrapeStreamMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*ScrapeStreamMessage_ScrapeInstruction
	//	*ScrapeStreamMessage_ConfigUpdate
	//	*ScrapeStreamMessage_ScrapeInformation
	Message isScrapeStreamMessage_Message `protobuf_oneof:"message"`
}

func (x *ScrapeStreamMessage) Reset() {
	*x = ScrapeStreamMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_controller_pb_controller_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScrapeStreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeStreamMessage) ProtoMessage() {}

func (x *ScrapeStreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controller_pb_controller_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeStreamMessage.ProtoReflect.Descriptor instead.
func (*ScrapeStreamMessage) Descriptor() ([]byte, []int) {
	return file_internal_controller_pb_controller_proto_rawDescGZIP(), []int{0}
}

func (m *ScrapeStreamMessage) GetMessage() isScrapeStreamMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *ScrapeStreamMessage) GetScrapeInstruction() *ScrapeInstruction {
	if x, ok := x.GetMessage().(*ScrapeStreamMessage_ScrapeInstruction); ok {
		return x.ScrapeInstruction
	}
	return nil
}

func (x *ScrapeStreamMessage) GetConfigUpdate() *AgentConfigUpdate {
	if x, ok := x.GetMessage().(*ScrapeStreamMessage_ConfigUpdate); ok {
		return x.ConfigUpdate
	}
	return nil
}

func (x *ScrapeStreamMessage) GetScrapeInformation() *ScrapeInformation {
	if x, ok := x.GetMessage().(*ScrapeStreamMessage_ScrapeInformation); ok {
		return x.ScrapeInformation
	}
	return nil
}

type isScrapeStreamMessage_Message interface {
	isScrapeStreamMessage_Message()
}

type ScrapeStreamMessage_ScrapeInstruction struct {
	// Should only be sent by the controller to an agent
	ScrapeInstruction *ScrapeInstruction `protobuf:"bytes,1,opt,name=scrape_instruction,json=scrapeInstruction,proto3,oneof"`
}

type ScrapeStreamMessage_ConfigUpdate struct {
	// Should only be sent by the controller to an agent
	ConfigUpdate *AgentConfigUpdate `protobuf:"bytes,2,opt,name=config_update,json=configUpdate,proto3,oneof"`
}

type ScrapeStreamMessage_ScrapeInformation struct {
	// Should only be sent by an agent to the controller
	ScrapeInformation *ScrapeInformation `protobuf:"bytes,3,opt,name=scrape_information,json=scrapeInformation,proto3,oneof"`
}

func (*ScrapeStreamMessage_ScrapeInstruction) isScrapeStreamMessage_Message() {}

func (*ScrapeStreamMessage_ConfigUpdate) isScrapeStreamMessage_Message() {}

func (*ScrapeStreamMessage_ScrapeInformation) isScrapeStreamMessage_Message() {}

// An instruction from the controller to agent of what to scrape
type ScrapeInstruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A list of URLs to scrape
	Urls []string `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *ScrapeInstruction) Reset() {
	*x = ScrapeInstruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_controller_pb_controller_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScrapeInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeInstruction) ProtoMessage() {}

func (x *ScrapeInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controller_pb_controller_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeInstruction.ProtoReflect.Descriptor instead.
func (*ScrapeInstruction) Descriptor() ([]byte, []int) {
	return file_internal_controller_pb_controller_proto_rawDescGZIP(), []int{1}
}

func (x *ScrapeInstruction) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

// Configuration update for the agent
type AgentConfigUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The timeout the agent should use for each single scrape
	SingleScrapeTimeoutMs int32 `protobuf:"varint,1,opt,name=single_scrape_timeout_ms,json=singleScrapeTimeoutMs,proto3" json:"single_scrape_timeout_ms,omitempty"`
}

func (x *AgentConfigUpdate) Reset() {
	*x = AgentConfigUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_controller_pb_controller_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfigUpdate) ProtoMessage() {}

func (x *AgentConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controller_pb_controller_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfigUpdate.ProtoReflect.Descriptor instead.
func (*AgentConfigUpdate) Descriptor() ([]byte, []int) {
	return file_internal_controller_pb_controller_proto_rawDescGZIP(), []int{2}
}

func (x *AgentConfigUpdate) GetSingleScrapeTimeoutMs() int32 {
	if x != nil {
		return x.SingleScrapeTimeoutMs
	}
	return 0
}

// Information about a single scrape operation (a single page request)
type ScrapeMetrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The total number of bytes downloaded during a single scrape
	ResponseSizeBytes int32 `protobuf:"varint,1,opt,name=response_size_bytes,json=responseSizeBytes,proto3" json:"response_size_bytes,omitempty"`
	// The status code from the main request
	HttpStatusCode int32 `protobuf:"varint,2,opt,name=http_status_code,json=httpStatusCode,proto3" json:"http_status_code,omitempty"`
	// The number of URLs in the found_urls list
	NumFoundUrls int32 `protobuf:"varint,3,opt,name=num_found_urls,json=numFoundUrls,proto3" json:"num_found_urls,omitempty"`
	// How long this individual scrape took to execute
	ScrapeDurationMs int32 `protobuf:"varint,4,opt,name=scrape_duration_ms,json=scrapeDurationMs,proto3" json:"scrape_duration_ms,omitempty"`
}

func (x *ScrapeMetrics) Reset() {
	*x = ScrapeMetrics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_controller_pb_controller_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScrapeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeMetrics) ProtoMessage() {}

func (x *ScrapeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controller_pb_controller_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeMetrics.ProtoReflect.Descriptor instead.
func (*ScrapeMetrics) Descriptor() ([]byte, []int) {
	return file_internal_controller_pb_controller_proto_rawDescGZIP(), []int{3}
}

func (x *ScrapeMetrics) GetResponseSizeBytes() int32 {
	if x != nil {
		return x.ResponseSizeBytes
	}
	return 0
}

func (x *ScrapeMetrics) GetHttpStatusCode() int32 {
	if x != nil {
		return x.HttpStatusCode
	}
	return 0
}

func (x *ScrapeMetrics) GetNumFoundUrls() int32 {
	if x != nil {
		return x.NumFoundUrls
	}
	return 0
}

func (x *ScrapeMetrics) GetScrapeDurationMs() int32 {
	if x != nil {
		return x.ScrapeDurationMs
	}
	return 0
}

// Information from scraping a single URL
type ScrapeInformation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The agent that scraped
	AgentId int32 `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// The URL scraped
	ScrapedUrl string `protobuf:"bytes,2,opt,name=scraped_url,json=scrapedUrl,proto3" json:"scraped_url,omitempty"`
	// The URLs found on the page
	FoundUrls []string `protobuf:"bytes,3,rep,name=found_urls,json=foundUrls,proto3" json:"found_urls,omitempty"`
	// Metrics from the scape
	Metrics *ScrapeMetrics `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	// If there was an error
	Error URLRequestErrorCode `protobuf:"varint,5,opt,name=error,proto3,enum=pb.URLRequestErrorCode" json:"error,omitempty"`
}

func (x *ScrapeInformation) Reset() {
	*x = ScrapeInformation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_controller_pb_controller_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScrapeInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeInformation) ProtoMessage() {}

func (x *ScrapeInformation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controller_pb_controller_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeInformation.ProtoReflect.Descriptor instead.
func (*ScrapeInformation) Descriptor() ([]byte, []int) {
	return file_internal_controller_pb_controller_proto_rawDescGZIP(), []int{4}
}

func (x *ScrapeInformation) GetAgentId() int32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *ScrapeInformation) GetScrapedUrl() string {
	if x != nil {
		return x.ScrapedUrl
	}
	return ""
}

func (x *ScrapeInformation) GetFoundUrls() []string {
	if x != nil {
		return x.FoundUrls
	}
	return nil
}

func (x *ScrapeInformation) GetMetrics() *ScrapeMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *ScrapeInformation) GetError() URLRequestErrorCode {
	if x != nil {
		return x.Error
	}
	return URLRequestErrorCode_NONE
}

// Register an agent with the controller
type RegisterAgentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The version of nomad the agent is using
	NomadVersion int64 `protobuf:"varint,1,opt,name=nomad_version,json=nomadVersion,proto3" json:"nomad_version,omitempty"`
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_controller_pb_controller_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controller_pb_controller_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_internal_controller_pb_controller_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterAgentRequest) GetNomadVersion() int64 {
	if x != nil {
		return x.NomadVersion
	}
	return 0
}

// Information for an agent requesting to be registered
type RegisterAgentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A unique ID for the agent assigned by the controller
	AgentId int32 `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// The config for the agent to use
	Config *AgentConfigUpdate `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	// If true, agent is wrong version and will not be registered
	VersionMismatch bool `protobuf:"varint,3,opt,name=version_mismatch,json=versionMismatch,proto3" json:"version_mismatch,omitempty"`
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_controller_pb_controller_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controller_pb_controller_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_internal_controller_pb_controller_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterAgentResponse) GetAgentId() int32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *RegisterAgentResponse) GetConfig() *AgentConfigUpdate {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RegisterAgentResponse) GetVersionMismatch() bool {
	if x != nil {
		return x.VersionMismatch
	}
	return false
}

var File_internal_controller_pb_controller_proto protoreflect.FileDescriptor

var file_internal_controller_pb_controller_proto_rawDesc = []byte{
	0x0a, 0x27, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xee, 0x01,
	0x0a, 0x13, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x46, 0x0a, 0x12, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x5f,
	0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x49, 0x6e, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x11, 0x73, 0x63, 0x72, 0x61,
	0x70, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x0a,
	0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x46, 0x0a, 0x12, 0x73,
	0x63, 0x72, 0x61, 0x70, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63, 0x72,
	0x61, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00,
	0x52, 0x11, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x27,
	0x0a, 0x11, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x22, 0x4c, 0x0a, 0x11, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x37, 0x0a, 0x18,
	0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x5f, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x5f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x15,
	0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x6f, 0x75, 0x74, 0x4d, 0x73, 0x22, 0xbd, 0x01, 0x0a, 0x0d, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65,
	0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x2e, 0x0a, 0x13, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x10, 0x68, 0x74, 0x74, 0x70, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0e, 0x68, 0x74, 0x74, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x24, 0x0a, 0x0e, 0x6e, 0x75, 0x6d, 0x5f, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x75,
	0x72, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6e, 0x75, 0x6d, 0x46, 0x6f,
	0x75, 0x6e, 0x64, 0x55, 0x72, 0x6c, 0x73, 0x12, 0x2c, 0x0a, 0x12, 0x73, 0x63, 0x72, 0x61, 0x70,
	0x65, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x10, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x22, 0xca, 0x01, 0x0a, 0x11, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65,
	0x64, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x63, 0x72,
	0x61, 0x70, 0x65, 0x64, 0x55, 0x72, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x6f, 0x75, 0x6e, 0x64,
	0x5f, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x66, 0x6f, 0x75,
	0x6e, 0x64, 0x55, 0x72, 0x6c, 0x73, 0x12, 0x2b, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63, 0x72,
	0x61, 0x70, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x12, 0x2d, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x3b, 0x0a, 0x14, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6e, 0x6f,
	0x6d, 0x61, 0x64, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0c, 0x6e, 0x6f, 0x6d, 0x61, 0x64, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22,
	0x8c, 0x01, 0x0a, 0x15, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x29, 0x0a, 0x10, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6d,
	0x69, 0x73, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x69, 0x73, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2a, 0x5a,
	0x0a, 0x13, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12,
	0x17, 0x0a, 0x13, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53,
	0x45, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x4e, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x02, 0x12, 0x0b, 0x0a,
	0x07, 0x54, 0x49, 0x4d, 0x45, 0x4f, 0x55, 0x54, 0x10, 0x03, 0x32, 0x92, 0x01, 0x0a, 0x0a, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x3e, 0x0a, 0x06, 0x53, 0x63, 0x72,
	0x61, 0x70, 0x65, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x17, 0x2e, 0x70,
	0x62, 0x2e, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x28, 0x01, 0x30, 0x01, 0x12, 0x44, 0x0a, 0x0d, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x73,
	0x69, 0x64, 0x65, 0x78, 0x2f, 0x6e, 0x6f, 0x6d, 0x61, 0x64, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_controller_pb_controller_proto_rawDescOnce sync.Once
	file_internal_controller_pb_controller_proto_rawDescData = file_internal_controller_pb_controller_proto_rawDesc
)

func file_internal_controller_pb_controller_proto_rawDescGZIP() []byte {
	file_internal_controller_pb_controller_proto_rawDescOnce.Do(func() {
		file_internal_controller_pb_controller_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_controller_pb_controller_proto_rawDescData)
	})
	return file_internal_controller_pb_controller_proto_rawDescData
}

var file_internal_controller_pb_controller_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_controller_pb_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_controller_pb_controller_proto_goTypes = []any{
	(URLRequestErrorCode)(0),      // 0: pb.URLRequestErrorCode
	(*ScrapeStreamMessage)(nil),   // 1: pb.ScrapeStreamMessage
	(*ScrapeInstruction)(nil),     // 2: pb.ScrapeInstruction
	(*AgentConfigUpdate)(nil),     // 3: pb.AgentConfigUpdate
	(*ScrapeMetrics)(nil),         // 4: pb.ScrapeMetrics
	(*ScrapeInformation)(nil),     // 5: pb.ScrapeInformation
	(*RegisterAgentRequest)(nil),  // 6: pb.RegisterAgentRequest
	(*RegisterAgentResponse)(nil), // 7: pb.RegisterAgentResponse
}
var file_internal_controller_pb_controller_proto_depIdxs = []int32{
	2, // 0: pb.ScrapeStreamMessage.scrape_instruction:type_name -> pb.ScrapeInstruction
	3, // 1: pb.ScrapeStreamMessage.config_update:type_name -> pb.AgentConfigUpdate
	5, // 2: pb.ScrapeStreamMessage.scrape_information:type_name -> pb.ScrapeInformation
	4, // 3: pb.ScrapeInformation.metrics:type_name -> pb.ScrapeMetrics
	0, // 4: pb.ScrapeInformation.error:type_name -> pb.URLRequestErrorCode
	3, // 5: pb.RegisterAgentResponse.config:type_name -> pb.AgentConfigUpdate
	1, // 6: pb.Controller.Scrape:input_type -> pb.ScrapeStreamMessage
	6, // 7: pb.Controller.RegisterAgent:input_type -> pb.RegisterAgentRequest
	1, // 8: pb.Controller.Scrape:output_type -> pb.ScrapeStreamMessage
	7, // 9: pb.Controller.RegisterAgent:output_type -> pb.RegisterAgentResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_internal_controller_pb_controller_proto_init() }
func file_internal_controller_pb_controller_proto_init() {
	if File_internal_controller_pb_controller_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_controller_pb_controller_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ScrapeStreamMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_controller_pb_controller_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ScrapeInstruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_controller_pb_controller_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AgentConfigUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_controller_pb_controller_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ScrapeMetrics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_controller_pb_controller_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ScrapeInformation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_controller_pb_controller_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*RegisterAgentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_controller_pb_controller_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*RegisterAgentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_controller_pb_controller_proto_msgTypes[0].OneofWrappers = []any{
		(*ScrapeStreamMessage_ScrapeInstruction)(nil),
		(*ScrapeStreamMessage_ConfigUpdate)(nil),
		(*ScrapeStreamMessage_ScrapeInformation)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_controller_pb_controller_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_controller_pb_controller_proto_goTypes,
		DependencyIndexes: file_internal_controller_pb_controller_proto_depIdxs,
		EnumInfos:         file_internal_controller_pb_controller_proto_enumTypes,
		MessageInfos:      file_internal_controller_pb_controller_proto_msgTypes,
	}.Build()
	File_internal_controller_pb_controller_proto = out.File
	file_internal_controller_pb_controller_proto_rawDesc = nil
	file_internal_controller_pb_controller_proto_goTypes = nil
	file_internal_controller_pb_controller_proto_depIdxs = nil
}
